import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      {/* Add Google Fonts link for Xanh Mono to ensure font loads in production (Vercel, etc.) */}
      <head>
        {/* Xanh Mono font from Google Fonts for all text elements */}
        <link
          href="https://fonts.googleapis.com/css2?family=Xanh+Mono:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      {/* Use flex column layout to anchor nav to bottom */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#2d2d2d] min-h-screen flex flex-col justify-between`}>
        {/* Header Section - persists across all pages */}
        <header className="w-full flex flex-col sm:flex-row items-center justify-between px-4 sm:px-8 py-4 bg-black gap-4 sm:gap-0">
          {/* Logo and Title */}
          <div className="flex items-center gap-3">
            {/* Logo image using next/image for optimization */}
            <Image
              src="/images/logo.png"
              alt="Classmate Logo"
              width={36}
              height={36}
              priority
              style={{ objectFit: 'contain' }}
            />
            {/* App title with Xanh Mono font */}
            <span className="text-2xl sm:text-3xl font-bold text-white" style={{ fontFamily: 'Xanh Mono, monospace' }}>Classmate</span>
          </div>
          {/* Navigation Links with Responsive Spacing */}
          <nav className="flex gap-6 sm:gap-14">
            <Link className="text-white text-base sm:text-lg hover:underline" style={{ fontFamily: 'Xanh Mono, monospace' }} href="/">Home</Link>
            <a className="text-white text-base sm:text-lg hover:underline" style={{ fontFamily: 'Xanh Mono, monospace' }} href="#">About</a>
            <a className="text-white text-base sm:text-lg hover:underline" style={{ fontFamily: 'Xanh Mono, monospace' }} href="#">Contact</a>
          </nav>
        </header>

        {/* Main content area for pages */}
        <main className="flex-1 flex flex-col min-h-[70vh]">
          {children}
        </main>

        {/* Bottom Navigation Bar - always at the bottom */}
        <nav className="w-full bg-black flex flex-wrap justify-center items-center gap-6 sm:gap-12 md:gap-20 py-4 sm:py-6">
          {/* Navigation Items with Pill Hover Effect */}
          {[
            { label: 'Assignments', href: '/assignments' },
            { label: 'Classwork', href: '/classwork' },
            { label: 'PYQs', href: '#' },
            { label: 'Sessions', href: '#' },
            { label: 'PBL', href: '#' },
          ].map((item) => (
            <Link
              key={item.label}
              href={item.href}
              className="text-white text-base sm:text-xl md:text-2xl cursor-pointer transition-colors duration-200 px-6 py-2 rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#fde7c3] hover:bg-[#fde7c3] hover:text-[#7a6a58] focus-visible:bg-[#fde7c3] focus-visible:text-[#7a6a58]"
              style={{ fontFamily: 'Xanh Mono, monospace' }}
              tabIndex={0}
            >
              {item.label}
            </Link>
          ))}
        </nav>
      </body>
    </html>
  );
}
